name: Test CI

on:
  pull_request:
    paths:
      - '**.version'

jobs:
  check_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Finding updated directories compared to master
        id: directories
        run: |
          echo "::set-output name=FILES::$(git diff --name-only master | jq -R -s -c 'split("\n")')"
      - name: Display docker containers to build
        uses: actions/github-script@v5
        env:
          DIR: ${{ steps.directories.outputs.DIR }}
        with:
          script: |
            const fs = require('fs')

            const toBuild = JSON.parse('[".github/workflows/ci.yaml","folder-a/README.md","folder-b/.version","folder-b/Dockerfile","folder-b/README.md",""]').filter((file) => {
                if (file.includes('.version') && fs.existsSync(`${file.split('/')[0]}/Dockerfile`)) {
                    return file
                }
            })

            let output = ''

            if (toBuild.length === 0) {
                console.log('#### No version file updated')
            } else {
                output = `#### Version files updated

                <details><summary>Show directories</summary>

                </details>

                *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            }

            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: output
            })